// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dictionaries

import (
	"sync"
)

// Ensure, that DictRepositoryMock does implement DictRepository.
// If this is not the case, regenerate this file with moq.
var _ DictRepository = &DictRepositoryMock{}

// DictRepositoryMock is a mock implementation of DictRepository.
//
//	func TestSomethingThatUsesDictRepository(t *testing.T) {
//
//		// make and configure a mocked DictRepository
//		mockedDictRepository := &DictRepositoryMock{
//			BuildingsListFunc: func() ([]*Building, error) {
//				panic("mock out the BuildingsList method")
//			},
//			EntriesByBuildingFunc: func(id uint) ([]*Entry, error) {
//				panic("mock out the EntriesByBuilding method")
//			},
//		}
//
//		// use mockedDictRepository in code that requires DictRepository
//		// and then make assertions.
//
//	}
type DictRepositoryMock struct {
	// BuildingsListFunc mocks the BuildingsList method.
	BuildingsListFunc func() ([]*Building, error)

	// EntriesByBuildingFunc mocks the EntriesByBuilding method.
	EntriesByBuildingFunc func(id uint) ([]*Entry, error)

	// calls tracks calls to the methods.
	calls struct {
		// BuildingsList holds details about calls to the BuildingsList method.
		BuildingsList []struct {
		}
		// EntriesByBuilding holds details about calls to the EntriesByBuilding method.
		EntriesByBuilding []struct {
			// ID is the id argument value.
			ID uint
		}
	}
	lockBuildingsList     sync.RWMutex
	lockEntriesByBuilding sync.RWMutex
}

// BuildingsList calls BuildingsListFunc.
func (mock *DictRepositoryMock) BuildingsList() ([]*Building, error) {
	if mock.BuildingsListFunc == nil {
		panic("DictRepositoryMock.BuildingsListFunc: method is nil but DictRepository.BuildingsList was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBuildingsList.Lock()
	mock.calls.BuildingsList = append(mock.calls.BuildingsList, callInfo)
	mock.lockBuildingsList.Unlock()
	return mock.BuildingsListFunc()
}

// BuildingsListCalls gets all the calls that were made to BuildingsList.
// Check the length with:
//
//	len(mockedDictRepository.BuildingsListCalls())
func (mock *DictRepositoryMock) BuildingsListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBuildingsList.RLock()
	calls = mock.calls.BuildingsList
	mock.lockBuildingsList.RUnlock()
	return calls
}

// EntriesByBuilding calls EntriesByBuildingFunc.
func (mock *DictRepositoryMock) EntriesByBuilding(id uint) ([]*Entry, error) {
	if mock.EntriesByBuildingFunc == nil {
		panic("DictRepositoryMock.EntriesByBuildingFunc: method is nil but DictRepository.EntriesByBuilding was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockEntriesByBuilding.Lock()
	mock.calls.EntriesByBuilding = append(mock.calls.EntriesByBuilding, callInfo)
	mock.lockEntriesByBuilding.Unlock()
	return mock.EntriesByBuildingFunc(id)
}

// EntriesByBuildingCalls gets all the calls that were made to EntriesByBuilding.
// Check the length with:
//
//	len(mockedDictRepository.EntriesByBuildingCalls())
func (mock *DictRepositoryMock) EntriesByBuildingCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockEntriesByBuilding.RLock()
	calls = mock.calls.EntriesByBuilding
	mock.lockEntriesByBuilding.RUnlock()
	return calls
}
