version: "2"

run:
  build-tags:
    - integration
    - pg_integration

output:
  formats:
    text:
      colors: true
  sort-order:
    - linter
    - severity
    - file

linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - copyloopvar
    - errcheck
    - gosec
    - govet
    - ineffassign
    - perfsprint
    - predeclared
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - testpackage
    - unconvert
    - unused
    - usestdlibvars

  settings:
    goconst:
      ignore-string-values:
        - "true"
        - "false"
    gosec:
      excludes:
        - G404
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
            - - Id
            - - upperCaseConst: true
          severity: warning
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA1029
        - -ST1003
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - linters:
          - staticcheck
        text: "ST1000:"
    paths:
      - third_party
      - builtin
      - examples
      - ".*_gen\\.go$"
      - "mock_.*\\.go$"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false