version: "2"
run:
  build-tags:
    - integration
    - pg_integration
output:
  sort-order:
    - linter
    - severity
    - file
linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - copyloopvar
    - exptostd
    - gosec
    - perfsprint
    - predeclared
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - testpackage
    - unconvert
    - usestdlibvars
    - usetesting
  settings:
    goconst:
      ignore-string-values:
        - "true"
        - "false"
    gosec:
      excludes:
        - G404
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
            - - Id
            - - upperCaseConst: true
          severity: warning
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA1029
        - -ST1003
        - -QF1001
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_gen\.go$
      - mock\_.*\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports