version: '2.1'

services:
  traefik:
    image: traefik:v2.1
    container_name: "traefik"
    ports:
      - 80:80
      - 443:443
      - 9999:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./_traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./_traefik/services:/etc/traefik/services"
      - "./letsencrypt:/letsencrypt/"


  dynasty:
    container_name: dynasty
    image: ivch/dynasty:latest
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #      args:
    #        - REPO=auth
    environment:
      - LOG_VERBOSE=true
      - HTTP_PORT=9001
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=dyndb
      - DB_PORT=5432
      - DB_SCHEMA=postgres
      - DB_SSL=disable
      - AUTH_JWT_SECRET=!covabunga!
      - USER_VERIFY_REG_CODE=false
    expose:
      - 9001
    #    ports:
    #      - 9001:9001
    depends_on:
      dyndb:
        condition: service_healthy

  dyndb:
    image: postgres:10.2
    command: postgres -c log_statement=all
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql"
      - "./.data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - 54322:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5