version: '2.1'

services:
  dyndb:
    image: postgres:10.2
    command: postgres -c log_statement=all
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql"
      - "./.data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - 54322:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5