http:
  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:9001"
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:9002"

  routers:
    user-public-register:
      rule: "Path(`/users/v1/register`)"
      service: "user-service"
      entryPoints:
        - "http"
      priority: 1
    user-private:
      rule: "PathPrefix(`/users`)"
      service: "user-service"
      entryPoints:
        - "http"
      middlewares:
        - "auth"
      priority: 2

    auth-public:
      rule: "PathPrefix(`/auth`)"
      service: "auth-service"
      entryPoints:
        - "http"

  middlewares:
    auth:
      forwardAuth:
        address: "http://auth-service:90002/auth/v1/gwfa"
