version: '2.1'

services:
  traefik:
    image: traefik:v2.1
    container_name: "traefik"
    ports:
      - 80:80
      - 443:443
      - 9999:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./_traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./_traefik/services:/etc/traefik/services"

  sampleservice:
    container_name: sample-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=sample
    expose:
      - 9005