providers:
  file:
    directory: "/etc/traefik/services"
#    filename: "/etc/traefik/services.yml"

log:
  level: "ERROR"

accessLog: {}

api:
  insecure: true

entryPoints:
  http:
    address: ":80"