providers:
  file:
    directory: "/etc/traefik/services"
    watch: true

log:
  level: "ERROR"

accessLog: {}

api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: i.chobotar@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"