providers:
  file:
    directory: "/etc/traefik/services"
    watch: true

log:
  level: "ERROR"

accessLog: {}

api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"