// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package users

import (
	"sync"
)

// Ensure, that UserRepositoryMock does implement UserRepository.
// If this is not the case, regenerate this file with moq.
var _ UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CountRecoveryCodesByUserIn24hFunc: func(userID uint) (int, error) {
//				panic("mock out the CountRecoveryCodesByUserIn24h method")
//			},
//			CreateRecoverCodeFunc: func(c *PasswordRecovery) error {
//				panic("mock out the CreateRecoverCode method")
//			},
//			CreateUserFunc: func(user *User) error {
//				panic("mock out the CreateUser method")
//			},
//			DeleteUserFunc: func(u *User) error {
//				panic("mock out the DeleteUser method")
//			},
//			FindUserByApartmentFunc: func(building uint, apt uint) (*User, error) {
//				panic("mock out the FindUserByApartment method")
//			},
//			GetFamilyMembersFunc: func(ownerID uint) ([]*User, error) {
//				panic("mock out the GetFamilyMembers method")
//			},
//			GetRecoveryCodeFunc: func(c *PasswordRecovery) (*PasswordRecovery, error) {
//				panic("mock out the GetRecoveryCode method")
//			},
//			GetRegCodeFunc: func() (string, error) {
//				panic("mock out the GetRegCode method")
//			},
//			GetUserByEmailFunc: func(email string) (*User, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByIDFunc: func(id uint) (*User, error) {
//				panic("mock out the GetUserByID method")
//			},
//			GetUserByPhoneFunc: func(phone string) (*User, error) {
//				panic("mock out the GetUserByPhone method")
//			},
//			ResetPasswordFunc: func(codeID uint, req *UserUpdate) error {
//				panic("mock out the ResetPassword method")
//			},
//			UpdateUserFunc: func(u *UserUpdate) error {
//				panic("mock out the UpdateUser method")
//			},
//			UseRegCodeFunc: func(code string) error {
//				panic("mock out the UseRegCode method")
//			},
//			ValidateRegCodeFunc: func(code string) error {
//				panic("mock out the ValidateRegCode method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CountRecoveryCodesByUserIn24hFunc mocks the CountRecoveryCodesByUserIn24h method.
	CountRecoveryCodesByUserIn24hFunc func(userID uint) (int, error)

	// CreateRecoverCodeFunc mocks the CreateRecoverCode method.
	CreateRecoverCodeFunc func(c *PasswordRecovery) error

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(user *User) error

	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(u *User) error

	// FindUserByApartmentFunc mocks the FindUserByApartment method.
	FindUserByApartmentFunc func(building uint, apt uint) (*User, error)

	// GetFamilyMembersFunc mocks the GetFamilyMembers method.
	GetFamilyMembersFunc func(ownerID uint) ([]*User, error)

	// GetRecoveryCodeFunc mocks the GetRecoveryCode method.
	GetRecoveryCodeFunc func(c *PasswordRecovery) (*PasswordRecovery, error)

	// GetRegCodeFunc mocks the GetRegCode method.
	GetRegCodeFunc func() (string, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(email string) (*User, error)

	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(id uint) (*User, error)

	// GetUserByPhoneFunc mocks the GetUserByPhone method.
	GetUserByPhoneFunc func(phone string) (*User, error)

	// ResetPasswordFunc mocks the ResetPassword method.
	ResetPasswordFunc func(codeID uint, req *UserUpdate) error

	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(u *UserUpdate) error

	// UseRegCodeFunc mocks the UseRegCode method.
	UseRegCodeFunc func(code string) error

	// ValidateRegCodeFunc mocks the ValidateRegCode method.
	ValidateRegCodeFunc func(code string) error

	// calls tracks calls to the methods.
	calls struct {
		// CountRecoveryCodesByUserIn24h holds details about calls to the CountRecoveryCodesByUserIn24h method.
		CountRecoveryCodesByUserIn24h []struct {
			// UserID is the userID argument value.
			UserID uint
		}
		// CreateRecoverCode holds details about calls to the CreateRecoverCode method.
		CreateRecoverCode []struct {
			// C is the c argument value.
			C *PasswordRecovery
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// User is the user argument value.
			User *User
		}
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// U is the u argument value.
			U *User
		}
		// FindUserByApartment holds details about calls to the FindUserByApartment method.
		FindUserByApartment []struct {
			// Building is the building argument value.
			Building uint
			// Apt is the apt argument value.
			Apt uint
		}
		// GetFamilyMembers holds details about calls to the GetFamilyMembers method.
		GetFamilyMembers []struct {
			// OwnerID is the ownerID argument value.
			OwnerID uint
		}
		// GetRecoveryCode holds details about calls to the GetRecoveryCode method.
		GetRecoveryCode []struct {
			// C is the c argument value.
			C *PasswordRecovery
		}
		// GetRegCode holds details about calls to the GetRegCode method.
		GetRegCode []struct {
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Email is the email argument value.
			Email string
		}
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// ID is the id argument value.
			ID uint
		}
		// GetUserByPhone holds details about calls to the GetUserByPhone method.
		GetUserByPhone []struct {
			// Phone is the phone argument value.
			Phone string
		}
		// ResetPassword holds details about calls to the ResetPassword method.
		ResetPassword []struct {
			// CodeID is the codeID argument value.
			CodeID uint
			// Req is the req argument value.
			Req *UserUpdate
		}
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// U is the u argument value.
			U *UserUpdate
		}
		// UseRegCode holds details about calls to the UseRegCode method.
		UseRegCode []struct {
			// Code is the code argument value.
			Code string
		}
		// ValidateRegCode holds details about calls to the ValidateRegCode method.
		ValidateRegCode []struct {
			// Code is the code argument value.
			Code string
		}
	}
	lockCountRecoveryCodesByUserIn24h sync.RWMutex
	lockCreateRecoverCode             sync.RWMutex
	lockCreateUser                    sync.RWMutex
	lockDeleteUser                    sync.RWMutex
	lockFindUserByApartment           sync.RWMutex
	lockGetFamilyMembers              sync.RWMutex
	lockGetRecoveryCode               sync.RWMutex
	lockGetRegCode                    sync.RWMutex
	lockGetUserByEmail                sync.RWMutex
	lockGetUserByID                   sync.RWMutex
	lockGetUserByPhone                sync.RWMutex
	lockResetPassword                 sync.RWMutex
	lockUpdateUser                    sync.RWMutex
	lockUseRegCode                    sync.RWMutex
	lockValidateRegCode               sync.RWMutex
}

// CountRecoveryCodesByUserIn24h calls CountRecoveryCodesByUserIn24hFunc.
func (mock *UserRepositoryMock) CountRecoveryCodesByUserIn24h(userID uint) (int, error) {
	if mock.CountRecoveryCodesByUserIn24hFunc == nil {
		panic("UserRepositoryMock.CountRecoveryCodesByUserIn24hFunc: method is nil but UserRepository.CountRecoveryCodesByUserIn24h was just called")
	}
	callInfo := struct {
		UserID uint
	}{
		UserID: userID,
	}
	mock.lockCountRecoveryCodesByUserIn24h.Lock()
	mock.calls.CountRecoveryCodesByUserIn24h = append(mock.calls.CountRecoveryCodesByUserIn24h, callInfo)
	mock.lockCountRecoveryCodesByUserIn24h.Unlock()
	return mock.CountRecoveryCodesByUserIn24hFunc(userID)
}

// CountRecoveryCodesByUserIn24hCalls gets all the calls that were made to CountRecoveryCodesByUserIn24h.
// Check the length with:
//
//	len(mockedUserRepository.CountRecoveryCodesByUserIn24hCalls())
func (mock *UserRepositoryMock) CountRecoveryCodesByUserIn24hCalls() []struct {
	UserID uint
} {
	var calls []struct {
		UserID uint
	}
	mock.lockCountRecoveryCodesByUserIn24h.RLock()
	calls = mock.calls.CountRecoveryCodesByUserIn24h
	mock.lockCountRecoveryCodesByUserIn24h.RUnlock()
	return calls
}

// CreateRecoverCode calls CreateRecoverCodeFunc.
func (mock *UserRepositoryMock) CreateRecoverCode(c *PasswordRecovery) error {
	if mock.CreateRecoverCodeFunc == nil {
		panic("UserRepositoryMock.CreateRecoverCodeFunc: method is nil but UserRepository.CreateRecoverCode was just called")
	}
	callInfo := struct {
		C *PasswordRecovery
	}{
		C: c,
	}
	mock.lockCreateRecoverCode.Lock()
	mock.calls.CreateRecoverCode = append(mock.calls.CreateRecoverCode, callInfo)
	mock.lockCreateRecoverCode.Unlock()
	return mock.CreateRecoverCodeFunc(c)
}

// CreateRecoverCodeCalls gets all the calls that were made to CreateRecoverCode.
// Check the length with:
//
//	len(mockedUserRepository.CreateRecoverCodeCalls())
func (mock *UserRepositoryMock) CreateRecoverCodeCalls() []struct {
	C *PasswordRecovery
} {
	var calls []struct {
		C *PasswordRecovery
	}
	mock.lockCreateRecoverCode.RLock()
	calls = mock.calls.CreateRecoverCode
	mock.lockCreateRecoverCode.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *UserRepositoryMock) CreateUser(user *User) error {
	if mock.CreateUserFunc == nil {
		panic("UserRepositoryMock.CreateUserFunc: method is nil but UserRepository.CreateUser was just called")
	}
	callInfo := struct {
		User *User
	}{
		User: user,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(user)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedUserRepository.CreateUserCalls())
func (mock *UserRepositoryMock) CreateUserCalls() []struct {
	User *User
} {
	var calls []struct {
		User *User
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// DeleteUser calls DeleteUserFunc.
func (mock *UserRepositoryMock) DeleteUser(u *User) error {
	if mock.DeleteUserFunc == nil {
		panic("UserRepositoryMock.DeleteUserFunc: method is nil but UserRepository.DeleteUser was just called")
	}
	callInfo := struct {
		U *User
	}{
		U: u,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(u)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedUserRepository.DeleteUserCalls())
func (mock *UserRepositoryMock) DeleteUserCalls() []struct {
	U *User
} {
	var calls []struct {
		U *User
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// FindUserByApartment calls FindUserByApartmentFunc.
func (mock *UserRepositoryMock) FindUserByApartment(building uint, apt uint) (*User, error) {
	if mock.FindUserByApartmentFunc == nil {
		panic("UserRepositoryMock.FindUserByApartmentFunc: method is nil but UserRepository.FindUserByApartment was just called")
	}
	callInfo := struct {
		Building uint
		Apt      uint
	}{
		Building: building,
		Apt:      apt,
	}
	mock.lockFindUserByApartment.Lock()
	mock.calls.FindUserByApartment = append(mock.calls.FindUserByApartment, callInfo)
	mock.lockFindUserByApartment.Unlock()
	return mock.FindUserByApartmentFunc(building, apt)
}

// FindUserByApartmentCalls gets all the calls that were made to FindUserByApartment.
// Check the length with:
//
//	len(mockedUserRepository.FindUserByApartmentCalls())
func (mock *UserRepositoryMock) FindUserByApartmentCalls() []struct {
	Building uint
	Apt      uint
} {
	var calls []struct {
		Building uint
		Apt      uint
	}
	mock.lockFindUserByApartment.RLock()
	calls = mock.calls.FindUserByApartment
	mock.lockFindUserByApartment.RUnlock()
	return calls
}

// GetFamilyMembers calls GetFamilyMembersFunc.
func (mock *UserRepositoryMock) GetFamilyMembers(ownerID uint) ([]*User, error) {
	if mock.GetFamilyMembersFunc == nil {
		panic("UserRepositoryMock.GetFamilyMembersFunc: method is nil but UserRepository.GetFamilyMembers was just called")
	}
	callInfo := struct {
		OwnerID uint
	}{
		OwnerID: ownerID,
	}
	mock.lockGetFamilyMembers.Lock()
	mock.calls.GetFamilyMembers = append(mock.calls.GetFamilyMembers, callInfo)
	mock.lockGetFamilyMembers.Unlock()
	return mock.GetFamilyMembersFunc(ownerID)
}

// GetFamilyMembersCalls gets all the calls that were made to GetFamilyMembers.
// Check the length with:
//
//	len(mockedUserRepository.GetFamilyMembersCalls())
func (mock *UserRepositoryMock) GetFamilyMembersCalls() []struct {
	OwnerID uint
} {
	var calls []struct {
		OwnerID uint
	}
	mock.lockGetFamilyMembers.RLock()
	calls = mock.calls.GetFamilyMembers
	mock.lockGetFamilyMembers.RUnlock()
	return calls
}

// GetRecoveryCode calls GetRecoveryCodeFunc.
func (mock *UserRepositoryMock) GetRecoveryCode(c *PasswordRecovery) (*PasswordRecovery, error) {
	if mock.GetRecoveryCodeFunc == nil {
		panic("UserRepositoryMock.GetRecoveryCodeFunc: method is nil but UserRepository.GetRecoveryCode was just called")
	}
	callInfo := struct {
		C *PasswordRecovery
	}{
		C: c,
	}
	mock.lockGetRecoveryCode.Lock()
	mock.calls.GetRecoveryCode = append(mock.calls.GetRecoveryCode, callInfo)
	mock.lockGetRecoveryCode.Unlock()
	return mock.GetRecoveryCodeFunc(c)
}

// GetRecoveryCodeCalls gets all the calls that were made to GetRecoveryCode.
// Check the length with:
//
//	len(mockedUserRepository.GetRecoveryCodeCalls())
func (mock *UserRepositoryMock) GetRecoveryCodeCalls() []struct {
	C *PasswordRecovery
} {
	var calls []struct {
		C *PasswordRecovery
	}
	mock.lockGetRecoveryCode.RLock()
	calls = mock.calls.GetRecoveryCode
	mock.lockGetRecoveryCode.RUnlock()
	return calls
}

// GetRegCode calls GetRegCodeFunc.
func (mock *UserRepositoryMock) GetRegCode() (string, error) {
	if mock.GetRegCodeFunc == nil {
		panic("UserRepositoryMock.GetRegCodeFunc: method is nil but UserRepository.GetRegCode was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetRegCode.Lock()
	mock.calls.GetRegCode = append(mock.calls.GetRegCode, callInfo)
	mock.lockGetRegCode.Unlock()
	return mock.GetRegCodeFunc()
}

// GetRegCodeCalls gets all the calls that were made to GetRegCode.
// Check the length with:
//
//	len(mockedUserRepository.GetRegCodeCalls())
func (mock *UserRepositoryMock) GetRegCodeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetRegCode.RLock()
	calls = mock.calls.GetRegCode
	mock.lockGetRegCode.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *UserRepositoryMock) GetUserByEmail(email string) (*User, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("UserRepositoryMock.GetUserByEmailFunc: method is nil but UserRepository.GetUserByEmail was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByEmailCalls())
func (mock *UserRepositoryMock) GetUserByEmailCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserByID calls GetUserByIDFunc.
func (mock *UserRepositoryMock) GetUserByID(id uint) (*User, error) {
	if mock.GetUserByIDFunc == nil {
		panic("UserRepositoryMock.GetUserByIDFunc: method is nil but UserRepository.GetUserByID was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	return mock.GetUserByIDFunc(id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByIDCalls())
func (mock *UserRepositoryMock) GetUserByIDCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}

// GetUserByPhone calls GetUserByPhoneFunc.
func (mock *UserRepositoryMock) GetUserByPhone(phone string) (*User, error) {
	if mock.GetUserByPhoneFunc == nil {
		panic("UserRepositoryMock.GetUserByPhoneFunc: method is nil but UserRepository.GetUserByPhone was just called")
	}
	callInfo := struct {
		Phone string
	}{
		Phone: phone,
	}
	mock.lockGetUserByPhone.Lock()
	mock.calls.GetUserByPhone = append(mock.calls.GetUserByPhone, callInfo)
	mock.lockGetUserByPhone.Unlock()
	return mock.GetUserByPhoneFunc(phone)
}

// GetUserByPhoneCalls gets all the calls that were made to GetUserByPhone.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByPhoneCalls())
func (mock *UserRepositoryMock) GetUserByPhoneCalls() []struct {
	Phone string
} {
	var calls []struct {
		Phone string
	}
	mock.lockGetUserByPhone.RLock()
	calls = mock.calls.GetUserByPhone
	mock.lockGetUserByPhone.RUnlock()
	return calls
}

// ResetPassword calls ResetPasswordFunc.
func (mock *UserRepositoryMock) ResetPassword(codeID uint, req *UserUpdate) error {
	if mock.ResetPasswordFunc == nil {
		panic("UserRepositoryMock.ResetPasswordFunc: method is nil but UserRepository.ResetPassword was just called")
	}
	callInfo := struct {
		CodeID uint
		Req    *UserUpdate
	}{
		CodeID: codeID,
		Req:    req,
	}
	mock.lockResetPassword.Lock()
	mock.calls.ResetPassword = append(mock.calls.ResetPassword, callInfo)
	mock.lockResetPassword.Unlock()
	return mock.ResetPasswordFunc(codeID, req)
}

// ResetPasswordCalls gets all the calls that were made to ResetPassword.
// Check the length with:
//
//	len(mockedUserRepository.ResetPasswordCalls())
func (mock *UserRepositoryMock) ResetPasswordCalls() []struct {
	CodeID uint
	Req    *UserUpdate
} {
	var calls []struct {
		CodeID uint
		Req    *UserUpdate
	}
	mock.lockResetPassword.RLock()
	calls = mock.calls.ResetPassword
	mock.lockResetPassword.RUnlock()
	return calls
}

// UpdateUser calls UpdateUserFunc.
func (mock *UserRepositoryMock) UpdateUser(u *UserUpdate) error {
	if mock.UpdateUserFunc == nil {
		panic("UserRepositoryMock.UpdateUserFunc: method is nil but UserRepository.UpdateUser was just called")
	}
	callInfo := struct {
		U *UserUpdate
	}{
		U: u,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(u)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockedUserRepository.UpdateUserCalls())
func (mock *UserRepositoryMock) UpdateUserCalls() []struct {
	U *UserUpdate
} {
	var calls []struct {
		U *UserUpdate
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}

// UseRegCode calls UseRegCodeFunc.
func (mock *UserRepositoryMock) UseRegCode(code string) error {
	if mock.UseRegCodeFunc == nil {
		panic("UserRepositoryMock.UseRegCodeFunc: method is nil but UserRepository.UseRegCode was just called")
	}
	callInfo := struct {
		Code string
	}{
		Code: code,
	}
	mock.lockUseRegCode.Lock()
	mock.calls.UseRegCode = append(mock.calls.UseRegCode, callInfo)
	mock.lockUseRegCode.Unlock()
	return mock.UseRegCodeFunc(code)
}

// UseRegCodeCalls gets all the calls that were made to UseRegCode.
// Check the length with:
//
//	len(mockedUserRepository.UseRegCodeCalls())
func (mock *UserRepositoryMock) UseRegCodeCalls() []struct {
	Code string
} {
	var calls []struct {
		Code string
	}
	mock.lockUseRegCode.RLock()
	calls = mock.calls.UseRegCode
	mock.lockUseRegCode.RUnlock()
	return calls
}

// ValidateRegCode calls ValidateRegCodeFunc.
func (mock *UserRepositoryMock) ValidateRegCode(code string) error {
	if mock.ValidateRegCodeFunc == nil {
		panic("UserRepositoryMock.ValidateRegCodeFunc: method is nil but UserRepository.ValidateRegCode was just called")
	}
	callInfo := struct {
		Code string
	}{
		Code: code,
	}
	mock.lockValidateRegCode.Lock()
	mock.calls.ValidateRegCode = append(mock.calls.ValidateRegCode, callInfo)
	mock.lockValidateRegCode.Unlock()
	return mock.ValidateRegCodeFunc(code)
}

// ValidateRegCodeCalls gets all the calls that were made to ValidateRegCode.
// Check the length with:
//
//	len(mockedUserRepository.ValidateRegCodeCalls())
func (mock *UserRepositoryMock) ValidateRegCodeCalls() []struct {
	Code string
} {
	var calls []struct {
		Code string
	}
	mock.lockValidateRegCode.RLock()
	calls = mock.calls.ValidateRegCode
	mock.lockValidateRegCode.RUnlock()
	return calls
}

// Ensure, that MailSenderMock does implement MailSender.
// If this is not the case, regenerate this file with moq.
var _ MailSender = &MailSenderMock{}

// MailSenderMock is a mock implementation of MailSender.
//
//	func TestSomethingThatUsesMailSender(t *testing.T) {
//
//		// make and configure a mocked MailSender
//		mockedMailSender := &MailSenderMock{
//			SendRecoveryCodeEmailFunc: func(to string, username string, code string) error {
//				panic("mock out the SendRecoveryCodeEmail method")
//			},
//		}
//
//		// use mockedMailSender in code that requires MailSender
//		// and then make assertions.
//
//	}
type MailSenderMock struct {
	// SendRecoveryCodeEmailFunc mocks the SendRecoveryCodeEmail method.
	SendRecoveryCodeEmailFunc func(to string, username string, code string) error

	// calls tracks calls to the methods.
	calls struct {
		// SendRecoveryCodeEmail holds details about calls to the SendRecoveryCodeEmail method.
		SendRecoveryCodeEmail []struct {
			// To is the to argument value.
			To string
			// Username is the username argument value.
			Username string
			// Code is the code argument value.
			Code string
		}
	}
	lockSendRecoveryCodeEmail sync.RWMutex
}

// SendRecoveryCodeEmail calls SendRecoveryCodeEmailFunc.
func (mock *MailSenderMock) SendRecoveryCodeEmail(to string, username string, code string) error {
	if mock.SendRecoveryCodeEmailFunc == nil {
		panic("MailSenderMock.SendRecoveryCodeEmailFunc: method is nil but MailSender.SendRecoveryCodeEmail was just called")
	}
	callInfo := struct {
		To       string
		Username string
		Code     string
	}{
		To:       to,
		Username: username,
		Code:     code,
	}
	mock.lockSendRecoveryCodeEmail.Lock()
	mock.calls.SendRecoveryCodeEmail = append(mock.calls.SendRecoveryCodeEmail, callInfo)
	mock.lockSendRecoveryCodeEmail.Unlock()
	return mock.SendRecoveryCodeEmailFunc(to, username, code)
}

// SendRecoveryCodeEmailCalls gets all the calls that were made to SendRecoveryCodeEmail.
// Check the length with:
//
//	len(mockedMailSender.SendRecoveryCodeEmailCalls())
func (mock *MailSenderMock) SendRecoveryCodeEmailCalls() []struct {
	To       string
	Username string
	Code     string
} {
	var calls []struct {
		To       string
		Username string
		Code     string
	}
	mock.lockSendRecoveryCodeEmail.RLock()
	calls = mock.calls.SendRecoveryCodeEmail
	mock.lockSendRecoveryCodeEmail.RUnlock()
	return calls
}
