// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package requests

import (
	"context"
	"github.com/ivch/dynasty/models/dto"
	"github.com/ivch/dynasty/models/entities"
	"sync"
)

var (
	lockrequestsRepositoryMockCreate                sync.RWMutex
	lockrequestsRepositoryMockDelete                sync.RWMutex
	lockrequestsRepositoryMockGetRequestByIDAndUser sync.RWMutex
	lockrequestsRepositoryMockListByUser            sync.RWMutex
	lockrequestsRepositoryMockListForGuard          sync.RWMutex
	lockrequestsRepositoryMockUpdate                sync.RWMutex
	lockrequestsRepositoryMockUpdateForGuard        sync.RWMutex
)

// Ensure, that requestsRepositoryMock does implement requestsRepository.
// If this is not the case, regenerate this file with moq.
var _ requestsRepository = &requestsRepositoryMock{}

// requestsRepositoryMock is a mock implementation of requestsRepository.
//
//     func TestSomethingThatUsesrequestsRepository(t *testing.T) {
//
//         // make and configure a mocked requestsRepository
//         mockedrequestsRepository := &requestsRepositoryMock{
//             CreateFunc: func(req *entities.Request) (uint, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(id uint, userID uint) error {
// 	               panic("mock out the Delete method")
//             },
//             GetRequestByIDAndUserFunc: func(id uint, userId uint) (*entities.Request, error) {
// 	               panic("mock out the GetRequestByIDAndUser method")
//             },
//             ListByUserFunc: func(r *dto.RequestListFilterRequest) ([]*entities.Request, error) {
// 	               panic("mock out the ListByUser method")
//             },
//             ListForGuardFunc: func(req *dto.RequestListFilterRequest) ([]*entities.Request, error) {
// 	               panic("mock out the ListForGuard method")
//             },
//             UpdateFunc: func(req *entities.Request) error {
// 	               panic("mock out the Update method")
//             },
//             UpdateForGuardFunc: func(id uint, status string) error {
// 	               panic("mock out the UpdateForGuard method")
//             },
//         }
//
//         // use mockedrequestsRepository in code that requires requestsRepository
//         // and then make assertions.
//
//     }
type requestsRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(req *entities.Request) (uint, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uint, userID uint) error

	// GetRequestByIDAndUserFunc mocks the GetRequestByIDAndUser method.
	GetRequestByIDAndUserFunc func(id uint, userId uint) (*entities.Request, error)

	// ListByUserFunc mocks the ListByUser method.
	ListByUserFunc func(r *dto.RequestListFilterRequest) ([]*entities.Request, error)

	// ListForGuardFunc mocks the ListForGuard method.
	ListForGuardFunc func(req *dto.RequestListFilterRequest) ([]*entities.Request, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(req *entities.Request) error

	// UpdateForGuardFunc mocks the UpdateForGuard method.
	UpdateForGuardFunc func(id uint, status string) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Req is the req argument value.
			Req *entities.Request
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uint
			// UserID is the userID argument value.
			UserID uint
		}
		// GetRequestByIDAndUser holds details about calls to the GetRequestByIDAndUser method.
		GetRequestByIDAndUser []struct {
			// ID is the id argument value.
			ID uint
			// UserId is the userId argument value.
			UserId uint
		}
		// ListByUser holds details about calls to the ListByUser method.
		ListByUser []struct {
			// R is the r argument value.
			R *dto.RequestListFilterRequest
		}
		// ListForGuard holds details about calls to the ListForGuard method.
		ListForGuard []struct {
			// Req is the req argument value.
			Req *dto.RequestListFilterRequest
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Req is the req argument value.
			Req *entities.Request
		}
		// UpdateForGuard holds details about calls to the UpdateForGuard method.
		UpdateForGuard []struct {
			// ID is the id argument value.
			ID uint
			// Status is the status argument value.
			Status string
		}
	}
}

// Create calls CreateFunc.
func (mock *requestsRepositoryMock) Create(req *entities.Request) (uint, error) {
	if mock.CreateFunc == nil {
		panic("requestsRepositoryMock.CreateFunc: method is nil but requestsRepository.Create was just called")
	}
	callInfo := struct {
		Req *entities.Request
	}{
		Req: req,
	}
	lockrequestsRepositoryMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockrequestsRepositoryMockCreate.Unlock()
	return mock.CreateFunc(req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedrequestsRepository.CreateCalls())
func (mock *requestsRepositoryMock) CreateCalls() []struct {
	Req *entities.Request
} {
	var calls []struct {
		Req *entities.Request
	}
	lockrequestsRepositoryMockCreate.RLock()
	calls = mock.calls.Create
	lockrequestsRepositoryMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *requestsRepositoryMock) Delete(id uint, userID uint) error {
	if mock.DeleteFunc == nil {
		panic("requestsRepositoryMock.DeleteFunc: method is nil but requestsRepository.Delete was just called")
	}
	callInfo := struct {
		ID     uint
		UserID uint
	}{
		ID:     id,
		UserID: userID,
	}
	lockrequestsRepositoryMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockrequestsRepositoryMockDelete.Unlock()
	return mock.DeleteFunc(id, userID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedrequestsRepository.DeleteCalls())
func (mock *requestsRepositoryMock) DeleteCalls() []struct {
	ID     uint
	UserID uint
} {
	var calls []struct {
		ID     uint
		UserID uint
	}
	lockrequestsRepositoryMockDelete.RLock()
	calls = mock.calls.Delete
	lockrequestsRepositoryMockDelete.RUnlock()
	return calls
}

// GetRequestByIDAndUser calls GetRequestByIDAndUserFunc.
func (mock *requestsRepositoryMock) GetRequestByIDAndUser(id uint, userId uint) (*entities.Request, error) {
	if mock.GetRequestByIDAndUserFunc == nil {
		panic("requestsRepositoryMock.GetRequestByIDAndUserFunc: method is nil but requestsRepository.GetRequestByIDAndUser was just called")
	}
	callInfo := struct {
		ID     uint
		UserId uint
	}{
		ID:     id,
		UserId: userId,
	}
	lockrequestsRepositoryMockGetRequestByIDAndUser.Lock()
	mock.calls.GetRequestByIDAndUser = append(mock.calls.GetRequestByIDAndUser, callInfo)
	lockrequestsRepositoryMockGetRequestByIDAndUser.Unlock()
	return mock.GetRequestByIDAndUserFunc(id, userId)
}

// GetRequestByIDAndUserCalls gets all the calls that were made to GetRequestByIDAndUser.
// Check the length with:
//     len(mockedrequestsRepository.GetRequestByIDAndUserCalls())
func (mock *requestsRepositoryMock) GetRequestByIDAndUserCalls() []struct {
	ID     uint
	UserId uint
} {
	var calls []struct {
		ID     uint
		UserId uint
	}
	lockrequestsRepositoryMockGetRequestByIDAndUser.RLock()
	calls = mock.calls.GetRequestByIDAndUser
	lockrequestsRepositoryMockGetRequestByIDAndUser.RUnlock()
	return calls
}

// ListByUser calls ListByUserFunc.
func (mock *requestsRepositoryMock) ListByUser(r *dto.RequestListFilterRequest) ([]*entities.Request, error) {
	if mock.ListByUserFunc == nil {
		panic("requestsRepositoryMock.ListByUserFunc: method is nil but requestsRepository.ListByUser was just called")
	}
	callInfo := struct {
		R *dto.RequestListFilterRequest
	}{
		R: r,
	}
	lockrequestsRepositoryMockListByUser.Lock()
	mock.calls.ListByUser = append(mock.calls.ListByUser, callInfo)
	lockrequestsRepositoryMockListByUser.Unlock()
	return mock.ListByUserFunc(r)
}

// ListByUserCalls gets all the calls that were made to ListByUser.
// Check the length with:
//     len(mockedrequestsRepository.ListByUserCalls())
func (mock *requestsRepositoryMock) ListByUserCalls() []struct {
	R *dto.RequestListFilterRequest
} {
	var calls []struct {
		R *dto.RequestListFilterRequest
	}
	lockrequestsRepositoryMockListByUser.RLock()
	calls = mock.calls.ListByUser
	lockrequestsRepositoryMockListByUser.RUnlock()
	return calls
}

// ListForGuard calls ListForGuardFunc.
func (mock *requestsRepositoryMock) ListForGuard(req *dto.RequestListFilterRequest) ([]*entities.Request, error) {
	if mock.ListForGuardFunc == nil {
		panic("requestsRepositoryMock.ListForGuardFunc: method is nil but requestsRepository.ListForGuard was just called")
	}
	callInfo := struct {
		Req *dto.RequestListFilterRequest
	}{
		Req: req,
	}
	lockrequestsRepositoryMockListForGuard.Lock()
	mock.calls.ListForGuard = append(mock.calls.ListForGuard, callInfo)
	lockrequestsRepositoryMockListForGuard.Unlock()
	return mock.ListForGuardFunc(req)
}

// ListForGuardCalls gets all the calls that were made to ListForGuard.
// Check the length with:
//     len(mockedrequestsRepository.ListForGuardCalls())
func (mock *requestsRepositoryMock) ListForGuardCalls() []struct {
	Req *dto.RequestListFilterRequest
} {
	var calls []struct {
		Req *dto.RequestListFilterRequest
	}
	lockrequestsRepositoryMockListForGuard.RLock()
	calls = mock.calls.ListForGuard
	lockrequestsRepositoryMockListForGuard.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *requestsRepositoryMock) Update(req *entities.Request) error {
	if mock.UpdateFunc == nil {
		panic("requestsRepositoryMock.UpdateFunc: method is nil but requestsRepository.Update was just called")
	}
	callInfo := struct {
		Req *entities.Request
	}{
		Req: req,
	}
	lockrequestsRepositoryMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockrequestsRepositoryMockUpdate.Unlock()
	return mock.UpdateFunc(req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedrequestsRepository.UpdateCalls())
func (mock *requestsRepositoryMock) UpdateCalls() []struct {
	Req *entities.Request
} {
	var calls []struct {
		Req *entities.Request
	}
	lockrequestsRepositoryMockUpdate.RLock()
	calls = mock.calls.Update
	lockrequestsRepositoryMockUpdate.RUnlock()
	return calls
}

// UpdateForGuard calls UpdateForGuardFunc.
func (mock *requestsRepositoryMock) UpdateForGuard(id uint, status string) error {
	if mock.UpdateForGuardFunc == nil {
		panic("requestsRepositoryMock.UpdateForGuardFunc: method is nil but requestsRepository.UpdateForGuard was just called")
	}
	callInfo := struct {
		ID     uint
		Status string
	}{
		ID:     id,
		Status: status,
	}
	lockrequestsRepositoryMockUpdateForGuard.Lock()
	mock.calls.UpdateForGuard = append(mock.calls.UpdateForGuard, callInfo)
	lockrequestsRepositoryMockUpdateForGuard.Unlock()
	return mock.UpdateForGuardFunc(id, status)
}

// UpdateForGuardCalls gets all the calls that were made to UpdateForGuard.
// Check the length with:
//     len(mockedrequestsRepository.UpdateForGuardCalls())
func (mock *requestsRepositoryMock) UpdateForGuardCalls() []struct {
	ID     uint
	Status string
} {
	var calls []struct {
		ID     uint
		Status string
	}
	lockrequestsRepositoryMockUpdateForGuard.RLock()
	calls = mock.calls.UpdateForGuard
	lockrequestsRepositoryMockUpdateForGuard.RUnlock()
	return calls
}

var (
	lockServiceMockCreate             sync.RWMutex
	lockServiceMockDelete             sync.RWMutex
	lockServiceMockGet                sync.RWMutex
	lockServiceMockGuardRequestList   sync.RWMutex
	lockServiceMockGuardUpdateRequest sync.RWMutex
	lockServiceMockMy                 sync.RWMutex
	lockServiceMockUpdate             sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             CreateFunc: func(ctx context.Context, r *dto.RequestCreateRequest) (*dto.RequestCreateResponse, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(ctx context.Context, r *dto.RequestByID) error {
// 	               panic("mock out the Delete method")
//             },
//             GetFunc: func(ctx context.Context, r *dto.RequestByID) (*dto.RequestByIDResponse, error) {
// 	               panic("mock out the Get method")
//             },
//             GuardRequestListFunc: func(ctx context.Context, r *dto.RequestListFilterRequest) ([]*dto.RequestForGuard, error) {
// 	               panic("mock out the GuardRequestList method")
//             },
//             GuardUpdateRequestFunc: func(ctx context.Context, r *dto.GuardUpdateRequest) error {
// 	               panic("mock out the GuardUpdateRequest method")
//             },
//             MyFunc: func(ctx context.Context, r *dto.RequestListFilterRequest) (*dto.RequestMyResponse, error) {
// 	               panic("mock out the My method")
//             },
//             UpdateFunc: func(ctx context.Context, r *dto.RequestUpdateRequest) error {
// 	               panic("mock out the Update method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, r *dto.RequestCreateRequest) (*dto.RequestCreateResponse, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, r *dto.RequestByID) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, r *dto.RequestByID) (*dto.RequestByIDResponse, error)

	// GuardRequestListFunc mocks the GuardRequestList method.
	GuardRequestListFunc func(ctx context.Context, r *dto.RequestListFilterRequest) ([]*dto.RequestForGuard, error)

	// GuardUpdateRequestFunc mocks the GuardUpdateRequest method.
	GuardUpdateRequestFunc func(ctx context.Context, r *dto.GuardUpdateRequest) error

	// MyFunc mocks the My method.
	MyFunc func(ctx context.Context, r *dto.RequestListFilterRequest) (*dto.RequestMyResponse, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, r *dto.RequestUpdateRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.RequestCreateRequest
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.RequestByID
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.RequestByID
		}
		// GuardRequestList holds details about calls to the GuardRequestList method.
		GuardRequestList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.RequestListFilterRequest
		}
		// GuardUpdateRequest holds details about calls to the GuardUpdateRequest method.
		GuardUpdateRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.GuardUpdateRequest
		}
		// My holds details about calls to the My method.
		My []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.RequestListFilterRequest
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *dto.RequestUpdateRequest
		}
	}
}

// Create calls CreateFunc.
func (mock *ServiceMock) Create(ctx context.Context, r *dto.RequestCreateRequest) (*dto.RequestCreateResponse, error) {
	if mock.CreateFunc == nil {
		panic("ServiceMock.CreateFunc: method is nil but Service.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.RequestCreateRequest
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockServiceMockCreate.Unlock()
	return mock.CreateFunc(ctx, r)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedService.CreateCalls())
func (mock *ServiceMock) CreateCalls() []struct {
	Ctx context.Context
	R   *dto.RequestCreateRequest
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.RequestCreateRequest
	}
	lockServiceMockCreate.RLock()
	calls = mock.calls.Create
	lockServiceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ServiceMock) Delete(ctx context.Context, r *dto.RequestByID) error {
	if mock.DeleteFunc == nil {
		panic("ServiceMock.DeleteFunc: method is nil but Service.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.RequestByID
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockServiceMockDelete.Unlock()
	return mock.DeleteFunc(ctx, r)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedService.DeleteCalls())
func (mock *ServiceMock) DeleteCalls() []struct {
	Ctx context.Context
	R   *dto.RequestByID
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.RequestByID
	}
	lockServiceMockDelete.RLock()
	calls = mock.calls.Delete
	lockServiceMockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ServiceMock) Get(ctx context.Context, r *dto.RequestByID) (*dto.RequestByIDResponse, error) {
	if mock.GetFunc == nil {
		panic("ServiceMock.GetFunc: method is nil but Service.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.RequestByID
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockServiceMockGet.Unlock()
	return mock.GetFunc(ctx, r)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedService.GetCalls())
func (mock *ServiceMock) GetCalls() []struct {
	Ctx context.Context
	R   *dto.RequestByID
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.RequestByID
	}
	lockServiceMockGet.RLock()
	calls = mock.calls.Get
	lockServiceMockGet.RUnlock()
	return calls
}

// GuardRequestList calls GuardRequestListFunc.
func (mock *ServiceMock) GuardRequestList(ctx context.Context, r *dto.RequestListFilterRequest) ([]*dto.RequestForGuard, error) {
	if mock.GuardRequestListFunc == nil {
		panic("ServiceMock.GuardRequestListFunc: method is nil but Service.GuardRequestList was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.RequestListFilterRequest
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockGuardRequestList.Lock()
	mock.calls.GuardRequestList = append(mock.calls.GuardRequestList, callInfo)
	lockServiceMockGuardRequestList.Unlock()
	return mock.GuardRequestListFunc(ctx, r)
}

// GuardRequestListCalls gets all the calls that were made to GuardRequestList.
// Check the length with:
//     len(mockedService.GuardRequestListCalls())
func (mock *ServiceMock) GuardRequestListCalls() []struct {
	Ctx context.Context
	R   *dto.RequestListFilterRequest
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.RequestListFilterRequest
	}
	lockServiceMockGuardRequestList.RLock()
	calls = mock.calls.GuardRequestList
	lockServiceMockGuardRequestList.RUnlock()
	return calls
}

// GuardUpdateRequest calls GuardUpdateRequestFunc.
func (mock *ServiceMock) GuardUpdateRequest(ctx context.Context, r *dto.GuardUpdateRequest) error {
	if mock.GuardUpdateRequestFunc == nil {
		panic("ServiceMock.GuardUpdateRequestFunc: method is nil but Service.GuardUpdateRequest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.GuardUpdateRequest
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockGuardUpdateRequest.Lock()
	mock.calls.GuardUpdateRequest = append(mock.calls.GuardUpdateRequest, callInfo)
	lockServiceMockGuardUpdateRequest.Unlock()
	return mock.GuardUpdateRequestFunc(ctx, r)
}

// GuardUpdateRequestCalls gets all the calls that were made to GuardUpdateRequest.
// Check the length with:
//     len(mockedService.GuardUpdateRequestCalls())
func (mock *ServiceMock) GuardUpdateRequestCalls() []struct {
	Ctx context.Context
	R   *dto.GuardUpdateRequest
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.GuardUpdateRequest
	}
	lockServiceMockGuardUpdateRequest.RLock()
	calls = mock.calls.GuardUpdateRequest
	lockServiceMockGuardUpdateRequest.RUnlock()
	return calls
}

// My calls MyFunc.
func (mock *ServiceMock) My(ctx context.Context, r *dto.RequestListFilterRequest) (*dto.RequestMyResponse, error) {
	if mock.MyFunc == nil {
		panic("ServiceMock.MyFunc: method is nil but Service.My was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.RequestListFilterRequest
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockMy.Lock()
	mock.calls.My = append(mock.calls.My, callInfo)
	lockServiceMockMy.Unlock()
	return mock.MyFunc(ctx, r)
}

// MyCalls gets all the calls that were made to My.
// Check the length with:
//     len(mockedService.MyCalls())
func (mock *ServiceMock) MyCalls() []struct {
	Ctx context.Context
	R   *dto.RequestListFilterRequest
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.RequestListFilterRequest
	}
	lockServiceMockMy.RLock()
	calls = mock.calls.My
	lockServiceMockMy.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ServiceMock) Update(ctx context.Context, r *dto.RequestUpdateRequest) error {
	if mock.UpdateFunc == nil {
		panic("ServiceMock.UpdateFunc: method is nil but Service.Update was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *dto.RequestUpdateRequest
	}{
		Ctx: ctx,
		R:   r,
	}
	lockServiceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockServiceMockUpdate.Unlock()
	return mock.UpdateFunc(ctx, r)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedService.UpdateCalls())
func (mock *ServiceMock) UpdateCalls() []struct {
	Ctx context.Context
	R   *dto.RequestUpdateRequest
} {
	var calls []struct {
		Ctx context.Context
		R   *dto.RequestUpdateRequest
	}
	lockServiceMockUpdate.RLock()
	calls = mock.calls.Update
	lockServiceMockUpdate.RUnlock()
	return calls
}
