http:
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:9002"

  routers:
    auth-public:
      rule: "PathPrefix(`/auth`)"
      service: "auth-service"
      entryPoints:
        - "http"
      tls:
        certresolver: sample
      middlewares:
        - "cors"
      priority: 10