http:
  middlewares:
    auth:
      forwardAuth:
        address: "http://auth-service:9002/auth/v1/gwfa"
        authResponseHeaders:
          - "X-Auth-User"
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowOrigin: "*"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlMaxAge: 100
        addVaryHeader: true
    devnull:
      replacePath:
        path: "/devnull"