http:
  routers:
    http-to-https:
      rule: "PathPrefix(`/`)"
      service: "dynasty"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
      priority: 100

    guard-api:
      rule: "PathPrefix(`/requests/v1/guard`)"
      service: "dynasty"
      entryPoints:
        - "https"
      tls:
        certResolver: le
      middlewares:
        - "cors"
        - "basicauth"
      priority: 60

    user-register:
      rule: "PathPrefix(`/users/v1/register`)"
      service: "dynasty"
      entryPoints:
        - "https"
      tls:
        certResolver: le
      middlewares:
        - "cors"
      priority: 50

    need-auth:
      rule: "PathPrefix(`/users`, `/requests`)"
      service: "dynasty"
      entryPoints:
        - "https"
      tls:
        certResolver: le
      middlewares:
        - "cors"
        - "auth"
      priority: 10

    main:
      rule: "PathPrefix(`/auth`, `/dictionary`, `/ui`)"
      service: "dynasty"
      entryPoints:
        - "https"
      tls:
        certResolver: le
      middlewares:
        - "cors"
      priority: 1