http:
  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:9001"

  routers:
    user-internal:
      rule: "PathPrefix(`/users/v1/internal`)"
      service: "user-service"
      entryPoints:
        - "http"
      priority: 100
      middlewares:
        - "devnull"

    user-public-register:
      rule: "Host(`ivch.dev`) && PathPrefix(`/users/v1/register`)"
      service: "user-service"
      entryPoints:
        - "https"
      tls:
        certResolver: le
      middlewares:
        - "cors"
      priority: 50

    user-private:
      rule: "Host(`ivch.dev`) && PathPrefix(`/users`)"
      service: "user-service"
      entryPoints:
        - "https"
      tls:
        certResolver: le
      middlewares:
        - "auth"
        - "cors"
      priority: 10

    user-http-to-https:
      rule: "PathPrefix(`/users`)"
      service: "user-service"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
      priority: 1