http:
  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:9001"

  routers:
    user-internal:
      rule: "PathPrefix(`/users/v1/internal`)"
      service: "user-service"
      entryPoints:
        - "https"
      priority: 100
      middlewares:
        - "devnull"

    user-public-register:
      rule: "PathPrefix(`/users/v1/register`)"
      service: "user-service"
      entryPoints:
        - "http"
      middlewares:
        - "cors"
      priority: 50

    user-private:
      rule: "PathPrefix(`/users`)"
      service: "user-service"
      entryPoints:
        - "http"
      middlewares:
        - "auth"
        - "cors"
      priority: 10