name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        env:
          MYTAG: $(git rev-parse --short "$GITHUB_SHA")
          GO111MODULE: on

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: Install linter
#        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
#
#      - name: Lint
#        run: $(go env GOPATH)/bin/golangci-lint run
#
#      - name: Test
#        run: make test

      - name: Test image
        run: echo $MYTAG

      - name: Test 2
        run: make testtag



#     - name: Get dependencies
#       run: |
#         go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#             dep ensure
#         fi
#  git rev-parse --short HEAD
#     - name: Build
#       run: go build -v .
